---
- name: Backup Cisco Switch Configs
  hosts: network
  gather_facts: no
  tasks:

    - name: Get current datetime
      ansible.builtin.set_fact:
        current_datetime: "{{ lookup('pipe', 'date +%Y%m%d_%H%M%S') }}"

    - name: Get switch hostname
      cisco.ios.ios_facts:

    - name: Save running config to file
      cisco.ios.ios_command:
        commands: show running-config
      register: config_output

    - name: Save config to local file
      copy:
        content: "{{ config_output.stdout[0] }}"
        dest: "/backup {{ current_datetime }}_{{ ansible_net_hostname }}.txt"
      delegate_to: localhost
