---
- name: Backup Cisco IOS Configuration with Timestamp
  hosts: network
  gather_facts: no
  connection: ansible.netcommon.network_cli

  vars:
    timestamp: "{{ lookup('pipe', 'date +%Y%m%d_%H%M%S') }}"

  tasks:
    - name: Backup running-config from switch
      cisco.ios.ios_config:
        backup: yes
      register: backup_result

    - name: Save backup to local file with timestamp
      copy:
        content: "{{ backup_result.backup_config }}"
        dest: "backups/{{ inventory_hostname }}_{{ timestamp }}.cfg"
      delegate_to: localhost
