---
- name: Gather facts from Cisco switches and export to CSV
  hosts: cisco_switches
  gather_facts: no
  connection: network_cli
  collections:
    - cisco.ios

  vars:
    output_file: "cisco_facts_output.csv"

  tasks:
    - name: Gather Cisco IOS facts
      ios_facts:

    - name: Extract relevant data
      set_fact:
        switch_data: >-
          {{
            {
              'hostname': ansible_facts.net_hostname | default(inventory_hostname),
              'serial': ansible_facts.net_serialnum | default('N/A'),
              'version': ansible_facts.net_version | default('N/A'),
              'interfaces': ansible_facts.net_interfaces | dict2items |
                            map(attribute='value.ipv4') |
                            select('defined') |
                            map(attribute='address') |
                            list | join(', ')
            }
          }}

    - name: Add to CSV file
      delegate_to: localhost
      run_once: true
      vars:
        csv_header: "Hostname,Serial Number,IOS Version,Interfaces"
      block:
        - name: Initialize CSV file with header
          copy:
            dest: "{{ output_file }}"
            content: "{{ csv_header }}\n"
          when: inventory_hostname == groups['cisco_switches'][0]

        - name: Append switch info to CSV
          lineinfile:
            path: "{{ output_file }}"
            line: "{{ switch_data.hostname }},{{ switch_data.serial }},{{ switch_data.version }},{{ switch_data.interfaces }}"
            create: yes
            insertafter: EOF

