---
- name: Configure L3 Interface on Cisco Switch
  hosts: network
  gather_facts: no

  tasks:

    - name: Build Layer 3 interface config
      set_fact:
        interface_config:
          - "interface {{ interface_name }}"
          - "ip address {{ ip_address }}"
          - "{% if enable_port == 'yes' %}no shutdown{% else %}shutdown{% endif %}"

    - name: Apply L3 interface config
      cisco.ios.ios_config:
        lines: "{{ interface_config }}"
