---
- name: Restore Cisco Switch Config
  hosts: network
  gather_facts: no

  vars:
    config_path: "backup_configs/{{ restore_date }}_{{ restore_hostname }}.txt"

  tasks:

    - name: Check if backup file exists
      stat:
        path: "{{ config_path }}"
      delegate_to: localhost
      register: backup_file

    - name: Fail if backup file is not found
      fail:
        msg: "Backup file {{ config_path }} does not exist!"
      when: not backup_file.stat.exists

    - name: Read backup config
      slurp:
        src: "{{ config_path }}"
      delegate_to: localhost
      register: slurped_config

    - name: Restore configuration
      cisco.ios.ios_config:
        lines: "{{ slurped_config.content | b64decode | splitlines() }}"
